version: "3"
services:
  selenoid:
    networks:
      selenoid: null
    image: "aerokube/selenoid:latest"
    ports:
      - "4444:4444"
    volumes:
      - ./src/test/resources/config:/etc/browser
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "-conf", "/etc/browser/browsers.json", "-container-network", "selenoid"]

  selenoid-ui:
    networks:
      selenoid: null
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

networks:
  selenoid:
    external: true
