version: "3"

networks:
  net:
    name: net

services:
  chrome:
    networks:
      - net
    image: "selenoid/chrome:100.0"
    
  selenoid:
    networks:
      - net
    image: "aerokube/selenoid:latest"
    ports:
      - "4444:4444"
    volumes:
      - ./src/test/resources/config:/etc/browser
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "-conf", "/etc/browser/browsers.json", "-container-network", "net"]

# включить, если нужно посмотреть визуалку прогона
  selenoid-ui:
    networks:
      - net
    image: "aerokube/selenoid-ui"
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  autotests:
    networks:
      - net
    volumes:
      - ./:/tests
    image: "openjdk:11"
    command: bash -c "
      apt update
      && apt install maven -y
      && mvn -version
      && java -version
      && echo "-----Finish_Build-----"
      && mvn test -f tests/pom.xml
      "
    depends_on:
      selenoid:
        condition: service_started
