version: "2.1"
services:
  selenoid:
    image: "aerokube/selenoid:latest"
    ports:
      - "4444:4444"
    volumes:
      - ./src/test/resources/config:/etc/browser
      - /var/run/docker.sock:/var/run/docker.sock
    command: [ "-conf", "/etc/browser/browsers.json"]
